{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3b8ea2d5-6e2d-41ea-a3e7-17e41fed3ec9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# From:\n",
    "# https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_adapt_hist_eq_3d.html#sphx-glr-auto-examples-color-exposure-plot-adapt-hist-eq-3d-py  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "2b320ffa-f895-40b7-bfbb-199b8b0fa796",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as patches\n",
    "from matplotlib import cm, colors\n",
    "from mpl_toolkits.mplot3d import Axes3D\n",
    "import napari\n",
    "import numpy as np\n",
    "from skimage import exposure, util\n",
    "import imageio as io\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "import matplotlib.pyplot as plt\n",
    "from DLC_for_WBFM.utils.projects.finished_project_data import ProjectData\n",
    "from sklearn.experimental import enable_iterative_imputer\n",
    "import napari\n",
    "from sklearn.impute import IterativeImputer\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b7e33790-01fb-47d2-b1c8-a3d482e80c86",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:root:Did not find file /scratch/zimmer/Charles/dlc_stacks/immobilized-2021_10_25/3-tracking/postprocessing/manual_behavior_annotation.xlsx\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=======================================\n",
      "Project data for directory:\n",
      "/scratch/zimmer/Charles/dlc_stacks/immobilized-2021_10_25 \n",
      "=======================================\n",
      "Found the following raw data files:\n",
      "red_data: True\n",
      "green_data: True\n",
      "============Segmentation===============\n",
      "raw_segmentation: True\n",
      "segmentation: True\n",
      "============Tracklets==================\n",
      "df_training_tracklets: True\n",
      "reindexed_masks_training: True\n",
      "============Traces=====================\n",
      "red_traces: True\n",
      "green_traces: True\n",
      "final_tracks: True\n",
      "behavior_annotations: False\n",
      "\n"
     ]
    }
   ],
   "source": [
    "fname = \"/scratch/zimmer/Charles/dlc_stacks/immobilized-2021_10_25/project_config.yaml\"\n",
    "project_data = ProjectData.load_final_project_data_from_config(fname)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "9d570d88-9079-4767-a626-8b76bbc69af3",
   "metadata": {},
   "outputs": [],
   "source": [
    "all_frames = project_data.raw_frames"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "7c310736-6076-48c6-a3f9-0579cb76139f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get a raw red-channel imraw_frames\n",
    "\n",
    "im_orig = all_frames[0].get_raw_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "fcf69a60-1aa2-4bff-96a2-ea75decaefe0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# from skimage.data import cells3d\n",
    "\n",
    "# im_orig = util.img_as_float(cells3d()[:, 1, :, :])  # grab just the nuclei\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "48ecae99-5362-4a91-a54b-2f7cf00681d3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "208"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.max(im_orig)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c769a489-f906-47e7-8734-227bd2e0adee",
   "metadata": {},
   "source": [
    "# Adaptive histograms"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "0145e7f2-6cd0-44d6-b997-65531db42492",
   "metadata": {},
   "outputs": [],
   "source": [
    "im_orig = im_orig / np.max(im_orig)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "fb3d3c49-5635-42cb-a917-0d51363ddc99",
   "metadata": {},
   "outputs": [],
   "source": [
    "kernel_size = (im_orig.shape[0] // 4,\n",
    "               im_orig.shape[1] // 5,\n",
    "               im_orig.shape[2] // 5)\n",
    "kernel_size = np.array(kernel_size)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "70903573-8fff-403e-99f5-ce678d78c7ce",
   "metadata": {},
   "outputs": [],
   "source": [
    "im_eq = exposure.equalize_adapthist(im_orig, kernel_size=kernel_size, clip_limit=0.1, nbins=256)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "807fcf91-6210-4abb-892c-2226ced930c6",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Image layer 'im_eq' at 0x7f068c88c9d0>"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 563, in run_until_complete\n",
      "    self._check_runnung()\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 526, in _check_runnung\n",
      "    'Cannot run the event loop while another loop is running')\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 563, in run_until_complete\n",
      "    self._check_runnung()\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 526, in _check_runnung\n",
      "    'Cannot run the event loop while another loop is running')\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in zmqstream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 448, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 477, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 563, in run_until_complete\n",
      "    self._check_runnung()\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 526, in _check_runnung\n",
      "    'Cannot run the event loop while another loop is running')\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    }
   ],
   "source": [
    "v = napari.view_image(im_orig, ndisplay=3)\n",
    "v.add_image(im_eq)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f103df0c-c464-4633-89c1-ffa11148638a",
   "metadata": {},
   "source": [
    "# Global histogram"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "7808331a-49a1-461f-952a-b05f84259025",
   "metadata": {},
   "outputs": [],
   "source": [
    "im_eq = exposure.equalize_hist(im_orig)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "7c54bde2-0e1e-4db0-8200-6fc01ede7bb5",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Image layer 'im_eq' at 0x7f069a083e10>"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 563, in run_until_complete\n",
      "    self._check_runnung()\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 526, in _check_runnung\n",
      "    'Cannot run the event loop while another loop is running')\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 563, in run_until_complete\n",
      "    self._check_runnung()\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 526, in _check_runnung\n",
      "    'Cannot run the event loop while another loop is running')\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    }
   ],
   "source": [
    "v = napari.view_image(im_orig, ndisplay=3)\n",
    "v.add_image(im_eq)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "780d1c1a-0931-4b7b-bc51-38eb2a5ef0a4",
   "metadata": {},
   "source": [
    "# Denoise using TV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "36a1c1df-0691-454c-99c2-cb363e9e637a",
   "metadata": {},
   "outputs": [],
   "source": [
    "from skimage.restoration import denoise_tv_chambolle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "38dc6726-0bf3-482f-af0b-adadd48853e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "im_denoise = denoise_tv_chambolle(im_orig)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "26774cd0-001e-4d6c-82f7-d1ae847e48bd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Image layer 'im_denoise' at 0x7f06842e2dd0>"
      ]
     },
     "execution_count": 43,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 563, in run_until_complete\n",
      "    self._check_runnung()\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 526, in _check_runnung\n",
      "    'Cannot run the event loop while another loop is running')\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/site-packages/jupyter_client/threaded.py\", line 121, in _handle_recv\n",
      "    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 563, in run_until_complete\n",
      "    self._check_runnung()\n",
      "  File \"/home/charles/anaconda3/envs/torch/lib/python3.7/asyncio/base_events.py\", line 526, in _check_runnung\n",
      "    'Cannot run the event loop while another loop is running')\n",
      "RuntimeError: Cannot run the event loop while another loop is running\n"
     ]
    }
   ],
   "source": [
    "v = napari.view_image(im_orig, ndisplay=3)\n",
    "v.add_image(im_denoise)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "825e3126-eb70-4a86-845b-02821931e74b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
